services:
  rabbitmq-server:
    container_name: rabbitmq-server
    image: rabbitmq:3.10-management-alpine
    restart: always
    networks:
      - biblioteca-net
    volumes:
      - rabbitmq-server-volume:/var/lib/rabbitmq

  redis-server:
    container_name: redis-server 
    image: redis:alpine
    restart: always
    networks:
      - biblioteca-net

  autenticacao-db:
    container_name: autenticacao-db
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=abc@123
      - PGDATA=/db/data
    networks:
      - biblioteca-net
    volumes:
      - autenticacao-db-volume:/db/data

  avaliacao-db:
    container_name: avaliacao-db
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=abc@123
      - PGDATA=/db/data
    networks:
      - biblioteca-net
    volumes:
      - avaliacao-db-volume:/db/data

  catalogo-db:
    container_name: catalogo-db
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=abc@123
      - PGDATA=/db/data
    networks:
      - biblioteca-net
    volumes:
      - catalogo-db-volume:/db/data

  circulacao-db:
    container_name: circulacao-db
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=abc@123
      - PGDATA=/db/data
    networks:
      - biblioteca-net
    volumes:
      - circulacao-db-volume:/db/data

  notificacao-db:
    container_name: notificacao-db
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=abc@123
      - PGDATA=/db/data
    networks:
      - biblioteca-net
    volumes:
      - notificacao-db-volume:/db/data

  catalogo-service:
    container_name: catalogo-service
    build:
      context: .
      dockerfile: ./services/catalogo/Dockerfile.api
    restart: always
    networks:
      - biblioteca-net
    depends_on:
      - rabbitmq-server
      - redis-server
      - catalogo-db

networks:
  biblioteca-net:

volumes:
  rabbitmq-server-volume:
  autenticacao-db-volume:
  avaliacao-db-volume:
  catalogo-db-volume:
  circulacao-db-volume:
  notificacao-db-volume:
