# Generated by Django 3.0.8 on 2020-09-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulacaoapp', '0002_auto_20200912_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='livro_id',
            field=models.UUIDField(default='b3d01420-c14d-47e6-8f93-511dc1db4feb'),
            preserve_default=False,
        ),
    ]
