# Generated by Django 3.0.8 on 2020-10-31 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circulacaoapp', '0005_auto_20201031_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suspensao',
            name='dias_restantes',
        ),
    ]
