# Generated by Django 3.0.8 on 2020-11-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulacaoapp', '0006_remove_suspensao_dias_restantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renovacao',
            name='agente',
        ),
        migrations.AddField(
            model_name='renovacao',
            name='usuario_id',
            field=models.UUIDField(default=None),
            preserve_default=False,
        ),
    ]
