# Generated by Django 3.0.8 on 2020-11-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulacaoapp', '0007_auto_20201101_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='maximo_renovacoes',
            field=models.BooleanField(default=False),
        ),
    ]
