# Generated by Django 3.0.8 on 2020-11-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulacaoapp', '0008_emprestimo_maximo_renovacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='exemplar_referencia',
            field=models.BooleanField(default=False),
        ),
    ]
