# Generated by Django 3.0.8 on 2020-11-02 23:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('circulacaoapp', '0009_emprestimo_exemplar_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspensao',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
