# Generated by Django 3.0.8 on 2020-11-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circulacaoapp', '0011_auto_20201103_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='disponivel',
            new_name='disponibilidade_retirada',
        ),
    ]
