# Generated by Django 3.0.8 on 2020-11-07 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circulacaoapp', '0012_auto_20201104_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['created']},
        ),
    ]
