# Generated by Django 3.0.8 on 2020-11-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulacaoapp', '0013_auto_20201107_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='disponibilidade_retirada',
            field=models.DateField(null=True),
        ),
    ]
