# Generated by Django 3.0.8 on 2021-09-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacaoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='censurada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='censurada',
            field=models.BooleanField(default=False),
        ),
    ]
