# Generated by Django 3.0.8 on 2021-09-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacaoapp', '0002_auto_20210910_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
