# Generated by Django 3.1.13 on 2021-09-30 14:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaSugestoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'listas_sugestoes',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SugestaoAquisicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('usuario_id', models.UUIDField()),
                ('livro_id', models.UUIDField(blank=True)),
                ('titulo', models.CharField(max_length=100)),
                ('autor_principal', models.CharField(max_length=100)),
                ('autores_secundarios', models.CharField(blank=True, max_length=200)),
                ('local_publicacao', models.CharField(blank=True, max_length=100)),
                ('editora', models.CharField(max_length=100)),
                ('ano_publicacao', models.CharField(blank=True, max_length=10)),
                ('volume', models.CharField(blank=True, max_length=10)),
                ('edicao', models.CharField(blank=True, max_length=10)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('cdu', models.CharField(blank=True, max_length=10)),
                ('cutter', models.CharField(blank=True, max_length=20)),
                ('paginas', models.CharField(blank=True, max_length=10)),
                ('comentario', models.TextField(blank=True)),
                ('quantidade_curtidas', models.IntegerField(default=0)),
                ('censurada', models.BooleanField(default=False)),
                ('lista_sugestoes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sugestoes', to='aquisicaoapp.listasugestoes')),
            ],
            options={
                'db_table': 'sugestoes_aquisicao',
                'ordering': ['-quantidade_curtidas', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Curtida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('usuario_id', models.UUIDField()),
                ('aviso', models.BooleanField(default=False)),
                ('sugestao_aquisicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curtidas', to='aquisicaoapp.sugestaoaquisicao')),
            ],
            options={
                'db_table': 'curtidas',
            },
        ),
        migrations.AddConstraint(
            model_name='curtida',
            constraint=models.UniqueConstraint(fields=('sugestao_aquisicao_id', 'usuario_id'), name='curtida_unica'),
        ),
    ]
