# Generated by Django 3.1.13 on 2021-10-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquisicaoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugestaoaquisicao',
            name='livro_id',
            field=models.UUIDField(null=True),
        ),
    ]
