# Generated by Django 3.0.8 on 2020-07-18 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('matricula', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=150)),
                ('email_institucional', models.EmailField(max_length=254)),
                ('email_pessoal', models.EmailField(blank=True, max_length=254)),
                ('vinculo', models.CharField(max_length=20)),
                ('url_foto', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
