# Generated by Django 3.0.8 on 2020-08-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacaoapp', '0002_auto_20200722_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('padrao', models.BooleanField()),
                ('max_livros', models.PositiveIntegerField()),
                ('max_dias', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'perfis',
            },
        ),
    ]
