# Generated by Django 3.0.8 on 2020-09-03 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacaoapp', '0004_usuario_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'permissoes',
            },
        ),
        migrations.CreateModel(
            name='PermissaoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='autenticacaoapp.Permissao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissoes', to='autenticacaoapp.Usuario')),
            ],
            options={
                'db_table': 'permissoes_usuarios',
            },
        ),
    ]
