# Generated by Django 3.0.8 on 2020-09-12 20:40

from django.db import migrations

def create_pefil_padrao(apps, schema_editor):
    Perfil = apps.get_model('autenticacaoapp', 'Perfil')
    Perfil.objects.create(
        descricao='Perfil Padrão',
        padrao=True,
        max_livros=3,
        max_dias=14
    )

class Migration(migrations.Migration):

    dependencies = [
        ('autenticacaoapp', '0006_auto_20200902_2207'),
    ]

    operations = [
        migrations.RunPython(create_pefil_padrao)
    ]
