# Generated by Django 3.0.8 on 2020-10-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacaoapp', '0008_auto_20201031_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='suspensao',
            field=models.DateField(null=True),
        ),
    ]
