# Generated by Django 3.0.8 on 2020-11-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacaoapp', '0009_usuario_suspensao'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='quantidade_renovacoes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
