# Generated by Django 3.0.8 on 2020-12-05 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacaoapp', '0010_perfil_quantidade_renovacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPromocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, null=True, unique=True)),
                ('codigo_utilizado', models.CharField(blank=True, max_length=20)),
                ('validade', models.DateTimeField()),
                ('bolsista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='codigos_promocao_utilizados', to='autenticacaoapp.Usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codigos_promocao', to='autenticacaoapp.Usuario')),
            ],
            options={
                'db_table': 'codigos_promocao',
            },
        ),
    ]
