# Generated by Django 3.0.8 on 2020-12-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacaoapp', '0011_codigopromocao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigopromocao',
            name='codigo',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
