# Generated by Django 3.0.8 on 2020-12-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacaoapp', '0012_auto_20201205_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigopromocao',
            name='codigo_utilizado',
        ),
    ]
