# Generated by Django 3.1.13 on 2021-10-02 11:54

from django.db import migrations

PERMISSOES = [
    ('lista_sugestoes.criar', 'Criar lista de sugestões'),
]

def create_permissoes(apps, schema_editor):
    Permissao = apps.get_model('autenticacaoapp', 'Permissao')
    for perm in PERMISSOES:
        Permissao.objects.create(codigo=perm[0], descricao=perm[1])

class Migration(migrations.Migration):

    dependencies = [
        ('autenticacaoapp', '0013_remove_codigopromocao_codigo_utilizado'),
    ]

    operations = [
        migrations.RunPython(create_permissoes),
    ]
