# Generated by Django 3.0.8 on 2021-03-06 13:07

import os
import json
from redis import Redis
from django.db import migrations

USUARIO_SISTEMA_ID = os.getenv('USUARIO_SISTEMA_ID')
REDIS_HOST = os.getenv('REDIS_HOST')
REDIS_DB = int(os.getenv('REDIS_DB'))

USUARIO_SISTEMA = {
    'matricula': '',
    'perfil': None,
    'lista_permissoes': [
        'emprestimo.fazer',
        'emprestimo.receber_devolucao',
        'suspensao.abonar',
        'livro.catalogar',
        'livro.modificar',
        'avaliacao.moderar',
        'avaliacao.selecionar',
        'bolsista.promover'
    ],
    'created': '',
    'updated': '',
    '_id': USUARIO_SISTEMA_ID,
    'nome': 'Sistema',
    'nome_completo': 'Sistema',
    'email_institucional': '',
    'email_pessoal': '',
    'vinculo': '',
    'url_foto': '',
    'suspensao': None
}

def create_usuario_sistema(apps, schema_editor):
    value = json.dumps(USUARIO_SISTEMA)
    con = Redis(host=REDIS_HOST, db=REDIS_DB)
    con.set(USUARIO_SISTEMA_ID, value)

class Migration(migrations.Migration):

    dependencies = [
        ('autenticacaoapp', '0013_remove_codigopromocao_codigo_utilizado'),
    ]

    operations = [
        migrations.RunPython(create_usuario_sistema)
    ]
