# Generated by Django 3.2.13 on 2022-05-25 22:46

import os
from django.db import migrations, transaction

AUTENTICACAO_USUARIO_ID = os.getenv('AUTENTICACAO_USUARIO_ID')
AVALIACAO_USUARIO_ID = os.getenv('AVALIACAO_USUARIO_ID')
CATALOGO_USUARIO_ID = os.getenv('CATALOGO_USUARIO_ID')
CIRCULACAO_USUARIO_ID = os.getenv('CIRCULACAO_USUARIO_ID')
NOTIFICACAO_USUARIO_ID = os.getenv('NOTIFICACAO_USUARIO_ID')

def create(user_model, usuario_model, permissao_model, permissao_usuario_model, username, usuario_id):
    user = user_model.objects.create_user(username, password=usuario_id)

    usuario = usuario_model.objects.create(
        _id=usuario_id,
        user=user,
        nome=username,
        nome_completo='',
        email_institucional='',
        vinculo='service',
        url_foto=''
    )
    
    permissao = permissao_model.objects.create(
        codigo=username, 
        descricao=username
    )

    permissao_usuario_model.objects.create(
        permissao=permissao,
        usuario=usuario
    )


def create_service_usuarios(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Usuario = apps.get_model('autenticacaoapp', 'Usuario')
    Permissao = apps.get_model('autenticacaoapp', 'Permissao')
    PermissaoUsuario = apps.get_model('autenticacaoapp', 'PermissaoUsuario')

    with transaction.atomic():
        create(User, Usuario, Permissao, PermissaoUsuario, 'autenticacao_service', AUTENTICACAO_USUARIO_ID)
        create(User, Usuario, Permissao, PermissaoUsuario, 'avaliacao_service', AVALIACAO_USUARIO_ID)
        create(User, Usuario, Permissao, PermissaoUsuario, 'catalogo_service', CATALOGO_USUARIO_ID)
        create(User, Usuario, Permissao, PermissaoUsuario, 'circulacao_service', CIRCULACAO_USUARIO_ID)
        create(User, Usuario, Permissao, PermissaoUsuario, 'notificacao_service', NOTIFICACAO_USUARIO_ID)

class Migration(migrations.Migration):

    dependencies = [
        ('autenticacaoapp', '0014_auto_20211002_0854'),
    ]

    operations = [
        migrations.RunPython(create_service_usuarios),
    ]
