# Generated by Django 3.0.8 on 2020-08-09 14:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('autor_principal', models.CharField(max_length=100)),
                ('autores_secundarios', models.CharField(blank=True, max_length=200)),
                ('local_publicacao', models.CharField(max_length=100)),
                ('editora', models.CharField(max_length=100)),
                ('ano_publicacao', models.CharField(max_length=10)),
                ('volume', models.CharField(blank=True, max_length=10)),
                ('edicao', models.CharField(blank=True, max_length=10)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('cdu', models.CharField(max_length=10)),
                ('cutter', models.CharField(max_length=20)),
                ('paginas', models.CharField(max_length=10)),
                ('foto_capa', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'livros',
                'ordering': ['titulo', 'autor_principal', 'autores_secundarios'],
            },
        ),
        migrations.CreateModel(
            name='LocalizacaoFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localicazao', models.CharField(max_length=200)),
                ('disponivel', models.BooleanField(default=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizacoes', to='catalogoapp.Livro')),
            ],
            options={
                'db_table': 'localizacoes_fisicas',
            },
        ),
        migrations.CreateModel(
            name='Indexador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexador', models.CharField(max_length=50)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexadores', to='catalogoapp.Livro')),
            ],
            options={
                'db_table': 'indexadores',
                'ordering': ['indexador'],
            },
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=8, unique=True)),
                ('referencia', models.BooleanField(default=False)),
                ('disponivel', models.BooleanField(default=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplares', to='catalogoapp.Livro')),
            ],
            options={
                'db_table': 'exemplares',
            },
        ),
    ]
