# Generated by Django 3.0.8 on 2020-08-30 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0004_auto_20200830_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localizacaofisica',
            old_name='localicazao',
            new_name='localizacao',
        ),
    ]
