# Generated by Django 3.0.8 on 2021-08-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0006_auto_20201031_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='foto_capa',
        ),
    ]
