# Generated by Django 3.0.8 on 2021-08-29 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0007_remove_livro_foto_capa'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoCapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('region', models.CharField(max_length=100)),
                ('bucket', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('livro', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='foto_capa', to='catalogoapp.Livro')),
            ],
            options={
                'db_table': 'fotos_capas',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='VersaoFotoCapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('version_id', models.CharField(max_length=100)),
                ('atual', models.BooleanField(default=True)),
                ('foto_capa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versoes', to='catalogoapp.FotoCapa')),
            ],
            options={
                'db_table': 'versoes_foto_capa',
                'ordering': ['created'],
            },
        ),
    ]
