# Generated by Django 3.0.8 on 2021-09-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0008_fotocapa_versaofotocapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='media_notas',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='livro',
            name='quantidade_avaliacoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livro',
            name='soma_notas',
            field=models.IntegerField(default=0),
        ),
    ]
