# Generated by Django 3.0.8 on 2021-09-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogoapp', '0009_auto_20210909_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='quantidade_avaliacoes',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='livro',
            name='soma_notas',
            field=models.FloatField(default=0),
        ),
    ]
